[build]
publish = "docs/_site"
command = """
  # 1. uv をインストール
  chmod +x ./setup-uv.sh && ./setup-uv.sh

  # 2. Quarto をインストール
  curl -Lo quarto.tar.gz https://quarto.org/download/latest/quarto-linux-amd64.tar.gz
  mkdir quarto  # 展開先ディレクトリを作成
  tar -xzf quarto.tar.gz --strip-components=1 -C quarto
  export PATH=$PATH:$PWD/quarto/bin  # ダウンロードしたバイナリをパスに追加

  # 3. 必要な Python モジュールをインストール
  uv sync

  # 4. ドキュメントをビルド
  export QUARTO_PYTHON=$(pwd)/.venv/bin/python
  quarto render docs
"""
