[project]
name = "pgot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.15"
dependencies = [
    "ipykernel==7.3.0",
    "matplotlib==3.11.0",
    "nbclient==0.11.0",
    "nbformat==5.11.0",
    "numba==0.66.0",
    "numpy==2.4.6",
    "pgw-metric-vendored",
    "pot==0.9.7",
    "pybind11==3.0.4",
    "scikit-learn==1.9.0",
    "scipy==1.18.0",
    "torch==2.13.0",
]

[tool.uv.sources]
pgw-metric-vendored = { path = "vendor" }
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pgot"]
