"""PGOT public API.

Implementations live in responsibility-specific modules; imports from the
package root remain available for compatibility with existing notebooks.
"""

from .gaussian import (
    Gaussian,
    GaussianMixture,
    GaussianW2,
    I,
    T_map_Gaussian,
    T_map_Gaussian_rand,
    T_mean,
    T_rand,
    alignment_objective,
    gaussian_W,
    gaussian_cost_matrix,
    gaussian_w2_squared,
    gmm_transform,
    grad,
    grad_gauss,
    proj_gradient_descent,
    proj_stiefel,
    sample_from_gmm,
)
from .mew import EW2, MEW2, MEW2_GM, MEW2_coup, aEW2
from .mgw import MGW2, MGW2_GM, MGW2_GM_coup, MGW2_coup, aMGW2_GM, aMGW2_GM_coup
from .partial_mgw import (
    alignment_grad,
    alignment_loss,
    barycentric_projection,
    gw_mean_distortion,
    matched_statistics,
    nearest_target_indices,
    pMGW2_coup,
    partial_mgw_barycentric_map,
    partial_projected_gradient_descent,
    validate_partial_coupling,
)
from .partial_ot import (
    compute_T_X_to_Z,
    compute_T_X_to_Z_C,
    compute_monge_map_matrix,
    densite_theorique2d,
    display_gmm,
    entropic_partial_barycentric_map,
    entropic_partial_coupling,
    entropic_partial_displacement_interpolation,
    entropic_partial_ot,
    gaussian_displacement_interpolation,
    normalize_cost,
    submixture_pdf,
    partial_wasserstein_lagrange_entropic,
    to_numpy,
)
from .metadata import (
    array_sha256,
    coupling_marginal_diagnostics,
    file_sha256,
    git_revision,
    runtime_environment,
    solve_id,
    write_figure_sidecar,
)
from .paper_figures import (
    make_figure1,
    make_figure2,
    make_figure3,
    make_figure5,
    make_figure6,
    make_figure7,
    solve_epot_panels,
    solve_point_cloud_matching,
    solve_figure5,
)
from .reproducibility import (
    DEFAULT_SEED,
    DEFAULT_SOURCE_DATE_EPOCH,
    freeze_output_timestamps,
    get_rng,
    set_reproducible,
    set_seed,
)

__all__ = [
    # Reproducibility
    "DEFAULT_SEED",
    "DEFAULT_SOURCE_DATE_EPOCH",
    "freeze_output_timestamps",
    "get_rng",
    "set_reproducible",
    "set_seed",
    # Gaussian models, geometry, and maps
    "Gaussian",
    "GaussianMixture",
    "GaussianW2",
    "I",
    "T_map_Gaussian",
    "T_map_Gaussian_rand",
    "T_mean",
    "T_rand",
    "alignment_objective",
    "gaussian_W",
    "gaussian_cost_matrix",
    "gaussian_w2_squared",
    "gmm_transform",
    "grad",
    "grad_gauss",
    "proj_gradient_descent",
    "proj_stiefel",
    "sample_from_gmm",
    # Mixture GW
    "MGW2",
    "MGW2_GM",
    "MGW2_GM_coup",
    "MGW2_coup",
    "aMGW2_GM",
    "aMGW2_GM_coup",
    # Embedded W2
    "EW2",
    "MEW2",
    "MEW2_GM",
    "MEW2_coup",
    "aEW2",
    # Partial OT and Figure 5 helpers
    "compute_T_X_to_Z",
    "compute_T_X_to_Z_C",
    "compute_monge_map_matrix",
    "densite_theorique2d",
    "display_gmm",
    "entropic_partial_barycentric_map",
    "entropic_partial_coupling",
    "entropic_partial_displacement_interpolation",
    "entropic_partial_ot",
    "gaussian_displacement_interpolation",
    "normalize_cost",
    "submixture_pdf",
    "partial_wasserstein_lagrange_entropic",
    "to_numpy",
    # Partial mixture GW
    "alignment_grad",
    "alignment_loss",
    "barycentric_projection",
    "gw_mean_distortion",
    "matched_statistics",
    "nearest_target_indices",
    "pMGW2_coup",
    "partial_mgw_barycentric_map",
    "partial_projected_gradient_descent",
    "validate_partial_coupling",
    # Paper figure pipelines and provenance
    "array_sha256",
    "coupling_marginal_diagnostics",
    "file_sha256",
    "git_revision",
    "make_figure1",
    "make_figure2",
    "make_figure3",
    "make_figure5",
    "make_figure6",
    "make_figure7",
    "runtime_environment",
    "solve_epot_panels",
    "solve_point_cloud_matching",
    "solve_figure5",
    "solve_id",
    "write_figure_sidecar",
]
